### PR TITLE
[FIX] Add `fUSDT` to `supportedCrossChainTokens`

### PR DESCRIPTION
**Pull request by yuripramos**

### CODE REVIEW

**Comment by chillvybz** [comment]
wait this isn't right we want exact match. not substring match

**Comment by yuripramos** [comment]
So we need to manually change the fUSDT symbol to USDT:

This is the currently fUSDT, and in the tokenlist doesn't exist USDT for fantom, but fUSDT and USDT have same token address(according to [coinmarketcap.com](http://coinmarketcap.com))
```
   {
     "name": "Frapped USDT",
     "address": "0x049d68029688eAbF473097a2fC38ef61633A3C7A",
     "symbol": "fUSDT",
     "decimals": 6,
     "chainId": 250,
     "logoURI": "https://assets.coingecko.com/coins/images/21949/small/frapped.png?1640322203"
   },
```

**Comment by chillvybz** [comment]
whats the bug tho?
Ur current fix is not right.

it's either we pick USDT over fUSDT in the token list or we introduce an alias array in the tokenlist

but please explain the bug more?

**Comment by yuripramos** [comment]
@chillvybz @8d526 I've just pushed one solution more elegant that didn't impact our `findTokenById`. 

Now the default `supportedCrossChainTokens` for Fantom is `fUSDT` instead of `USDT`.

**Comment by chillvybz** [comment]
This looks more correct. thanks @yuripramos

**Pull request merged**
