### PR TITLE
[FEATURE] Enable status tab on main menu - Rework

### PR DESCRIPTION
**Pull request by yuripramos**
Rework from #85 now closed, to improve organization (the last PR was from one personal repo of mine) and many conflicts to solve since the implementation of some linting rules.

# Description

This PR Includes the new TAB status and the refactor over `this.loadBalances()` within WalletHome to make `loadBalances` accessible through context.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manually testing between swapping the Networks (avalanche, BSC and so on)

# Checklist from last PR

| Issue  |      Fixed?      |  reproduced the error locally? |
|----------|:-------------:|------:|
| [warning: key prop in react](https://github.com/polkaswitch/polkaswitch-ui/pull/85#issuecomment-996906130) |  ✅ | ✅ |
| [wallet displays empty state](https://github.com/polkaswitch/polkaswitch-ui/pull/85#issuecomment-996906130) |    ✅   |   ✅ |
| [infinite loop useLoadBalance](https://github.com/polkaswitch/polkaswitch-ui/pull/85#issuecomment-996910200) | ✅ |    ✅ |
| [new connext overwrite](https://github.com/polkaswitch/polkaswitch-ui/pull/85#issuecomment-996940568) | please QA |   ❌ |
| [anonymous func + bind(this) issue within hook](https://github.com/polkaswitch/polkaswitch-ui/pull/85#discussion_r771620183) | ✅ |    ✅ |

### CODE REVIEW

**Comment by chillvybz** [comment]
Can you merge latest development?

**Comment by chillvybz** [comment]
Wallet Tab seems to be still broken. Status tab looks better

**Comment by yuripramos** [comment]
Feedbacks addressed, PR updated 📗

**Comment by chillvybz** [comment]
Wallet tab working better, but one issue:
- if you are in a disconnected state and then connect. the wallet tab does not refresh and does not show the empty-state.
-

**Comment by yuripramos** [comment]
> Wallet tab working better, but one issue:
> 
> * if you are in a disconnected state and then connect. the wallet tab does not refresh and does not show the empty-state.
> 
> otherwise it looks good

Changed a bit the approach within useLoadBalance. Now it's fixed

**Comment by chillvybz** [comment]
Hm WalletTab looks better, but now the Status tab seems to have regressed:
image

**Comment by yuripramos** [comment]
> Hm WalletTab looks better, but now the Status tab seems to have regressed:
> image

This an edge case that happens only when the user do hard-refresh within the **STATUS TAB**. If the user swap between tabs after loading the balances, works as expected. I've just pushed one fix for that to ensure the node list being loaded every time the user lands on the component `StatusHome`

**Comment by chillvybz** [comment]
actually Yuri, i just realized your Status Tab logic isn't correct.
All it is checking for is if network.enabled?  which is wrong.
We want to check for if the RPC URL associated with the network is responding well.

**Comment by chillvybz** [comment]
In my test, I see that the xDai RPC is failing and returning 429 status (Because it is over the rate-limit) however status tab is showing it is GREEN, which is incorrect

**Comment by yuripramos** [comment]
As discussed in pvt now the logic uses the validation across `currentBalance` of each network, not only `network.enaled`

**Comment by chillvybz** [comment]
I'm going to merge but Status Tab fails to show nothing in disconnected state. It should at least say "Connect Wallet".

**Pull request merged**
